### ISSUE TITLE
Unable to install better-sqlite3

### ISSUE THREAD

**Issue by Deducts** [Deducts/DFrnkk7swNii4Pj#1]
Hello there! the title says it all. I am completely unable to install better-sqlite3 etc. This is a requirement for some of the things i am running. (OS is Ubuntu 64bit)

Even when following these, they dont supply enough help to be useful;
https://www.npmjs.com/package/better-sqlite3
https://github.com/JoshuaWise/better-sqlite3/blob/HEAD/docs/troubleshooting.md

```
billyserver@billyserver:~/Documents/Bot$ sudo npm install --save better-sqlite3

> integer@2.1.0 install /home/billyserver/Documents/Bot/node_modules/integer
> node-gyp rebuild

make: Entering directory '/home/billyserver/Documents/Bot/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
  SOLINK_MODULE(target) Release/obj.target/integer.node
  COPY Release/integer.node
  COPY ../build/integer.node
  TOUCH Release/obj.target/place_resulting_binary.stamp
make: Leaving directory '/home/billyserver/Documents/Bot/node_modules/integer/build'

> better-sqlite3@5.4.3 install /home/billyserver/Documents/Bot/node_modules/better-sqlite3
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 794, in Write
    extra_mac_bundle_resources, part_of_all)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 978, in WriteActions
    part_of_all=part_of_all, command=name)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1724, in WriteDoCmd
    force = True)
  File "/usr/local/lib/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1779, in WriteMakeRule
    cmddigest = hashlib.sha1(command if command else self.target).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/usr/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/billyserver/Documents/Bot/node_modules/better-sqlite3
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
npm WARN bot@1.0.0 No description
npm WARN bot@1.0.0 No repository field.
npm ERR! Linux 5.0.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "better-sqlite3"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! better-sqlite3@5.4.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@5.4.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the better-sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs better-sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls better-sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/billyserver/Documents/Bot/npm-debug.log

```

**Comment by fengkx** [comment]
Python2 is required
